### ISSUE TITLE
InstantView does not pop-up from any youtube homepage links any more?

### ISSUE THREAD

**Issue by JackDinn** [afrmtbl/InstantView#40]
So it was working for a couple of days but now it just refuses to launch the pop-out player from any thumbnail/link on the youtube "home" page. All other links/thumbnails like from the subscriptions, trending or recommended list on the right hand side of playing videos all launch the pop-out player fine.

Iv tried on chrome and chromium.

**Comment by afrmtbl** [comment]
Should be fixed in a5e1b86eb75d6864bade4795d18286107a99967d
The update is now pending on the Chrome Web Store :)

**Comment by JackDinn** [comment]
Ahha, Excellent news, and great work. Thx.

**Comment by JackDinn** [comment]
darn, i cant figure how to build it from here. I shall just have to wait until its released before i can check it out.

**Comment by afrmtbl** [comment]
Yeah I admit the build system is not very great. I started this project a while ago and haven't yet changed it.

**Comment by JackDinn** [comment]
Ok received the update. Working great, thx.
